"""Configuration helpers for paths, bounds, and public runtime defaults."""

from __future__ import annotations

from spatial_vtk.config.bounds import load_bounds_presets, preset_keywords, resolve_named_bounds
from spatial_vtk.config.labels import (
    METRIC_DISPLAY_NAMES,
    VALUE_COLUMN_LABELS,
    COLUMN_DISPLAY_LABELS,
    available_dashboard_value_columns,
    band_display_label,
    band_display_options,
    column_display_lookup,
    column_display_name,
    display_label,
    display_table,
    metric_display_name,
    normalize_metric_name,
    transform_display_options,
    value_column_display_name,
)
from spatial_vtk.config.metric_catalog import (
    ALL_METRIC_GROUPS,
    ALL_METRICS,
    DEFAULT_METRICS_BY_GROUP,
    LEGACY_METRIC_ALIASES,
    metric_group_for,
    normalize_metric_groups,
    resolve_metric_names,
)
from spatial_vtk.config.naming import abbreviate_model
from spatial_vtk.config.notebook import (
    format_run_time,
    notebook_timer,
    notebook_timing_enabled,
    print_run_time,
    register_svtk_cell_timer,
    register_svtk_time_magic,
)
from spatial_vtk.config.outputs import (
    OutputSpec,
    default_output_registry,
    infer_output_key,
    output_description,
    output_spec,
    resolve_output_path,
)
from spatial_vtk.config.paths import ROOT_DIR, ensure_dir
from spatial_vtk.config.metrics import (
    DEFAULT_METRIC_GROUPS,
    DEFAULT_METRICS,
    DEFAULT_OUTPUT_MODE,
    DEFAULT_TRANSFORMS,
    VALID_OUTPUT_MODES,
    VALID_TRANSFORMS,
    MetricSettings,
    SpectralSettings,
    metric_settings_summary,
    metrics_settings_from_config,
    transform_columns,
)
from spatial_vtk.config.runtime import (
    SVTK_CONFIG_ENV,
    SpatialVTKConfig,
    active_config,
    apply_run_scenario,
    clear_active_config,
    deep_merge,
    find_config_file,
    load_config,
    resolve_path,
    resolve_run_defaults,
)

__all__ = [
    "ROOT_DIR",
    "DEFAULT_METRIC_GROUPS",
    "DEFAULT_METRICS",
    "DEFAULT_OUTPUT_MODE",
    "DEFAULT_TRANSFORMS",
    "VALID_OUTPUT_MODES",
    "VALID_TRANSFORMS",
    "ALL_METRIC_GROUPS",
    "ALL_METRICS",
    "DEFAULT_METRICS_BY_GROUP",
    "LEGACY_METRIC_ALIASES",
    "MetricSettings",
    "OutputSpec",
    "SpectralSettings",
    "SVTK_CONFIG_ENV",
    "SpatialVTKConfig",
    "METRIC_DISPLAY_NAMES",
    "VALUE_COLUMN_LABELS",
    "COLUMN_DISPLAY_LABELS",
    "abbreviate_model",
    "active_config",
    "apply_run_scenario",
    "clear_active_config",
    "available_dashboard_value_columns",
    "band_display_label",
    "band_display_options",
    "column_display_lookup",
    "column_display_name",
    "deep_merge",
    "default_output_registry",
    "display_label",
    "display_table",
    "ensure_dir",
    "find_config_file",
    "format_run_time",
    "load_bounds_presets",
    "load_config",
    "infer_output_key",
    "metric_display_name",
    "metric_group_for",
    "metric_settings_summary",
    "metrics_settings_from_config",
    "notebook_timer",
    "notebook_timing_enabled",
    "normalize_metric_groups",
    "normalize_metric_name",
    "output_description",
    "output_spec",
    "preset_keywords",
    "print_run_time",
    "register_svtk_cell_timer",
    "register_svtk_time_magic",
    "resolve_output_path",
    "resolve_path",
    "resolve_named_bounds",
    "resolve_metric_names",
    "resolve_run_defaults",
    "transform_display_options",
    "transform_columns",
    "value_column_display_name",
]
