"""Spatial calculation helpers."""

from __future__ import annotations

from spatial_vtk.spatial.calculate.clustering import assign_redcap_clusters, run_residual_feature_clustering
from spatial_vtk.spatial.calculate.correlation import (
    build_distance_bin_summary,
    build_directional_distance_bin_summary,
    compute_global_morans_i,
    evaluate_spatial_block_holdouts,
    moran_result_to_frame,
)
from spatial_vtk.spatial.calculate.corridors import (
    BoundaryCorridorConfig,
    BoundaryCorridorWorkflowResult,
    CorridorAnchorConfig,
    CorridorSelectionConfig,
    PolygonCorridorConfig,
    boundary_corridor_config_from_config,
    build_boundary_corridors,
    build_station_edge_corridors,
    classify_records_by_corridors,
    run_boundary_corridor_workflow,
    run_boundary_corridor_workflow_from_config,
    select_records_by_corridors,
    select_events_in_corridors,
    serialize_corridor_geometries,
    summarize_corridor_event_counts,
)
from spatial_vtk.spatial.calculate.geojson import (
    GeoJSONNoOverlapError,
    GeoJSONPathControl,
    GeoJSONRegionSummaryWorkflowResult,
    add_geojson_metadata_to_metrics,
    annotate_points_with_geojson,
    apply_geojson_path_control,
    build_geojson_region_summary,
    build_geojson_region_summary_from_table,
    classify_paths_with_geojson,
    geojson_polygon_preview_table,
    load_geojson_polygons,
    run_geojson_region_summary_workflow,
    run_geojson_region_summary_workflow_from_config,
    select_geojson_polygons,
    summarize_metrics_by_geojson,
)
from spatial_vtk.spatial.calculate.geometry import add_source_station_geometry, forward_azimuth_deg
from spatial_vtk.spatial.calculate.geology import add_station_geology_classes, bootstrap_contrast_table, run_geology_spatial_tests
from spatial_vtk.spatial.calculate.patterns import build_pattern_similarity_station_anomalies, pattern_similarity
from spatial_vtk.spatial.calculate.paths import build_path_table, summarize_residuals_by_path_bin
from spatial_vtk.spatial.calculate.pca import PCASpatialModeResult, compute_pca_spatial_modes
from spatial_vtk.spatial.calculate.polygon_edges import load_polygon_features, select_near_edge_stations
from spatial_vtk.spatial.calculate.prepare_stats import (
    build_metric_field,
    build_station_feature_table,
    center_field_by_event,
    normalize_metrics_table,
    summarize_station_bias,
)
from spatial_vtk.spatial.calculate.rotation import rotate_ne_to_rt, rotate_rt_to_ne
from spatial_vtk.spatial.calculate.settings import SpatialStatisticsSettings, spatial_statistics_settings_from_config
from spatial_vtk.spatial.calculate.workflow import (
    SPATIAL_DERIVED_OUTPUT_KEYS,
    SPATIAL_STATISTICS_OUTPUT_DESCRIPTIONS,
    SPATIAL_STATISTICS_OUTPUT_NAMES,
    SPATIAL_SUMMARY_OUTPUT_KEYS,
    SpatialDerivedOutputsWorkflowResult,
    SpatialStatisticsWorkflowResult,
    run_spatial_derived_outputs_workflow,
    run_spatial_derived_outputs_workflow_from_config,
    run_spatial_statistics_workflow,
    run_spatial_statistics_workflow_from_config,
    spatial_statistics_output_paths,
)

__all__ = [
    "add_source_station_geometry",
    "add_station_geology_classes",
    "add_geojson_metadata_to_metrics",
    "annotate_points_with_geojson",
    "apply_geojson_path_control",
    "assign_redcap_clusters",
    "BoundaryCorridorConfig",
    "BoundaryCorridorWorkflowResult",
    "build_distance_bin_summary",
    "build_directional_distance_bin_summary",
    "build_boundary_corridors",
    "build_geojson_region_summary",
    "build_metric_field",
    "build_path_table",
    "build_pattern_similarity_station_anomalies",
    "build_station_edge_corridors",
    "build_station_feature_table",
    "boundary_corridor_config_from_config",
    "bootstrap_contrast_table",
    "center_field_by_event",
    "classify_paths_with_geojson",
    "classify_records_by_corridors",
    "compute_global_morans_i",
    "compute_pca_spatial_modes",
    "CorridorAnchorConfig",
    "CorridorSelectionConfig",
    "evaluate_spatial_block_holdouts",
    "forward_azimuth_deg",
    "GeoJSONNoOverlapError",
    "GeoJSONPathControl",
    "GeoJSONRegionSummaryWorkflowResult",
    "geojson_polygon_preview_table",
    "load_polygon_features",
    "load_geojson_polygons",
    "moran_result_to_frame",
    "normalize_metrics_table",
    "PCASpatialModeResult",
    "pattern_similarity",
    "PolygonCorridorConfig",
    "rotate_ne_to_rt",
    "rotate_rt_to_ne",
    "run_geology_spatial_tests",
    "run_boundary_corridor_workflow",
    "run_boundary_corridor_workflow_from_config",
    "run_geojson_region_summary_workflow",
    "run_geojson_region_summary_workflow_from_config",
    "run_residual_feature_clustering",
    "select_records_by_corridors",
    "select_events_in_corridors",
    "select_geojson_polygons",
    "select_near_edge_stations",
    "serialize_corridor_geometries",
    "SPATIAL_DERIVED_OUTPUT_KEYS",
    "SPATIAL_STATISTICS_OUTPUT_DESCRIPTIONS",
    "SPATIAL_STATISTICS_OUTPUT_NAMES",
    "SPATIAL_SUMMARY_OUTPUT_KEYS",
    "SpatialDerivedOutputsWorkflowResult",
    "SpatialStatisticsWorkflowResult",
    "SpatialStatisticsSettings",
    "run_spatial_derived_outputs_workflow",
    "run_spatial_derived_outputs_workflow_from_config",
    "run_spatial_statistics_workflow",
    "run_spatial_statistics_workflow_from_config",
    "spatial_statistics_output_paths",
    "spatial_statistics_settings_from_config",
    "summarize_corridor_event_counts",
    "build_geojson_region_summary_from_table",
    "summarize_metrics_by_geojson",
    "summarize_residuals_by_path_bin",
    "summarize_station_bias",
]
