name: spatial-vtk
channels:
  - conda-forge
dependencies:
  - python>=3.10,<3.13
  - contextily
  - h5py
  - ipykernel
  - matplotlib
  - nbsphinx
  - numpy
  - obspy
  - pandas
  - plotly
  - pyproj
  - pytest
  - pyyaml
  - scikit-learn
  - scipy
  - shapely
  - sphinx
  - sphinx-rtd-theme
  - streamlit
  - pip
  - pip:
      - build
      - streamlit-folium>=0.26
