"""Input/output helpers for manifests and waveform format handling."""

from __future__ import annotations

from spatial_vtk.io.artifacts import (
    ArtifactRecord,
    ArtifactRegistry,
    ArtifactSpec,
    artifact_manifest_path,
    artifact_path_for_spec,
    canonical_json,
    read_artifact_manifest,
    stable_hash,
    write_artifact_manifest,
)
from spatial_vtk.io.catalogs import context_dataset_paths, read_event_patch_table, read_events, read_stations
from spatial_vtk.io.compute_manifest import atomic_write_csv, ensure_run_dir, read_json, utc_run_id, write_json
from spatial_vtk.io.inventory import DEFAULT_WAVEFORM_SUFFIXES, build_file_inventory, build_observed_synthetic_inventory, compute_sha256
from spatial_vtk.io.kml import write_station_event_kml
from spatial_vtk.io.layouts import inspect_station_event_layouts
from spatial_vtk.io.metadata import (
    prepare_event_metadata,
    prepare_event_station_table,
    prepare_station_metadata,
    read_event_metadata,
    read_event_station_table,
    read_station_metadata,
)
from spatial_vtk.io.master_lists import (
    build_master_event_list,
    build_master_station_list,
    normalize_event_table,
    normalize_station_table,
    write_master_event_list,
    write_master_station_list,
)
from spatial_vtk.io.metric_inputs import (
    METRIC_QC_COLUMNS,
    METRIC_WAVEFORM_COLUMNS,
    comparison_qc_passed,
    metric_qc_lookup,
    metric_qc_passed,
    normalize_metric_qc_table,
    normalize_metric_waveform_inventory,
)
from spatial_vtk.io.model_aliases import (
    ModelFolderCandidate,
    ModelResolution,
    available_base_models,
    classify_model_folder,
    normalize_model_alias,
    resolve_model_aliases,
    scan_synthetic_model_folders,
)
from spatial_vtk.io.output_paths import default_output_paths
from spatial_vtk.io.plans import (
    MetricCompleteness,
    MetricPlan,
    compare_metric_plan_to_table,
    expected_metric_rows_from_inventory,
    metric_plan_from_config,
)
from spatial_vtk.io.preprocessing import (
    DEFAULT_SOURCE_COLUMN_CANDIDATES,
    WaveformPreprocessingWorkflowResult,
    preprocess_waveform_files,
)
from spatial_vtk.io.synthetic_formats import SyntheticFormatInfo, inspect_synthetic_format, synthetic_reader_for
from spatial_vtk.io.tables import (
    aggregate_metric_by_station_over_events,
    load_csv_bundle,
    load_output_table,
    normalize_metric_table,
    preview_output_table,
    preview_table,
    read_config_table,
    read_table,
    write_named_tables,
    write_output_table,
    write_output_tables,
    write_table,
    written_files_table,
    wide_to_long_metrics,
)
from spatial_vtk.io.waveforms import (
    PreprocessedWaveform,
    WaveformPreprocessing,
    apply_waveform_preprocessing_with_metadata,
    apply_waveform_preprocessing,
    load_waveform_collection,
    preprocess_stream,
    read_waveform_file,
    stream_station_table,
    trace_metadata_table,
    waveform_preprocessing_from_config,
    waveform_preprocessing_label,
    write_trace_metadata_csv,
)

__all__ = [
    "ArtifactRecord",
    "ArtifactRegistry",
    "ArtifactSpec",
    "DEFAULT_WAVEFORM_SUFFIXES",
    "DEFAULT_SOURCE_COLUMN_CANDIDATES",
    "MetricPlan",
    "MetricCompleteness",
    "ModelFolderCandidate",
    "ModelResolution",
    "METRIC_QC_COLUMNS",
    "METRIC_WAVEFORM_COLUMNS",
    "PreprocessedWaveform",
    "SyntheticFormatInfo",
    "WaveformPreprocessing",
    "WaveformPreprocessingWorkflowResult",
    "atomic_write_csv",
    "aggregate_metric_by_station_over_events",
    "apply_waveform_preprocessing",
    "apply_waveform_preprocessing_with_metadata",
    "artifact_manifest_path",
    "artifact_path_for_spec",
    "available_base_models",
    "build_master_event_list",
    "build_master_station_list",
    "build_file_inventory",
    "build_observed_synthetic_inventory",
    "classify_model_folder",
    "compare_metric_plan_to_table",
    "comparison_qc_passed",
    "compute_sha256",
    "canonical_json",
    "context_dataset_paths",
    "default_output_paths",
    "ensure_run_dir",
    "expected_metric_rows_from_inventory",
    "inspect_synthetic_format",
    "inspect_station_event_layouts",
    "load_csv_bundle",
    "load_output_table",
    "metric_plan_from_config",
    "metric_qc_lookup",
    "metric_qc_passed",
    "normalize_metric_table",
    "normalize_metric_qc_table",
    "normalize_metric_waveform_inventory",
    "normalize_event_table",
    "normalize_model_alias",
    "normalize_station_table",
    "prepare_event_metadata",
    "prepare_event_station_table",
    "prepare_station_metadata",
    "preview_output_table",
    "preview_table",
    "preprocess_stream",
    "preprocess_waveform_files",
    "read_event_patch_table",
    "read_artifact_manifest",
    "read_config_table",
    "read_event_metadata",
    "read_events",
    "read_event_station_table",
    "read_json",
    "read_stations",
    "read_station_metadata",
    "read_table",
    "read_waveform_file",
    "resolve_model_aliases",
    "scan_synthetic_model_folders",
    "stable_hash",
    "stream_station_table",
    "synthetic_reader_for",
    "trace_metadata_table",
    "utc_run_id",
    "waveform_preprocessing_from_config",
    "waveform_preprocessing_label",
    "wide_to_long_metrics",
    "write_artifact_manifest",
    "write_master_event_list",
    "write_master_station_list",
    "write_station_event_kml",
    "write_named_tables",
    "write_output_table",
    "write_output_tables",
    "write_table",
    "write_trace_metadata_csv",
    "written_files_table",
    "write_json",
    "load_waveform_collection",
]
