"""Visualization and dashboard preparation modules."""

from __future__ import annotations

from spatial_vtk.visualize.dashboard import (
    build_dashboard_summaries,
    dashboard_summary_input_columns,
    launch_configured_metrics_dashboard,
    launch_configured_qc_dashboard,
    launch_metrics_dashboard,
    launch_qc_dashboard,
    load_dashboard_metric_dataset,
    prepare_dashboard_metric_table,
    write_configured_dashboard_datasets,
    write_dashboard_metric_dataset,
    write_dashboard_summaries,
    write_dashboard_summary_dataset,
)
from spatial_vtk.visualize.figure_io import DEFAULT_FIGURE_NAMES, default_figure_paths, finish_figure, savefig
from spatial_vtk.visualize.figure_sidecars import (
    FigureSidecarResult,
    figure_sidecar_dimension_counts,
    figure_sidecar_metadata_path,
    figure_sidecar_status_frame,
    finish_figure_with_sidecar,
    layered_figure_rows,
    read_figure_sidecar_metadata,
    sidecar_rows_for_write,
    write_figure_row_sidecar,
)
from spatial_vtk.visualize.figure_context import (
    apply_figure_context,
    context_value_label,
    figure_context_lines,
    figure_context_text,
    is_log2_ratio_field,
    log2_effect_to_percent,
)
from spatial_vtk.visualize.context import (
    plot_event_magnitude_map,
    plot_station_event_beachball_map,
    plot_station_event_network_map,
)
from spatial_vtk.visualize.record_sections import (
    build_record_section_rows,
    plot_observed_synthetic_record_section,
    plot_record_section,
)
from spatial_vtk.visualize.qc import (
    build_trace_qc_overview_html,
    filter_trace_summary,
    plot_data_synthetic_availability,
    plot_event_station_retention_heatmap,
    plot_post_qc_station_event_map,
    plot_qc_drop_cause_diagnostics,
    plot_retention_summary,
    plot_trace_inventory_samples,
    queue_rows_from_filtered_trace_df,
    write_trace_qc_overview_html,
)
from spatial_vtk.visualize.waveforms import (
    plot_event_radial_trace_section,
    plot_event_trace_comparison,
    plot_station_event_waveform_map,
    plot_waveform_overlay_matrix,
)

__all__ = [
    "DEFAULT_FIGURE_NAMES",
    "FigureSidecarResult",
    "apply_figure_context",
    "build_record_section_rows",
    "build_dashboard_summaries",
    "build_trace_qc_overview_html",
    "context_value_label",
    "dashboard_summary_input_columns",
    "default_figure_paths",
    "figure_context_lines",
    "figure_context_text",
    "figure_sidecar_dimension_counts",
    "figure_sidecar_metadata_path",
    "figure_sidecar_status_frame",
    "filter_trace_summary",
    "finish_figure",
    "finish_figure_with_sidecar",
    "is_log2_ratio_field",
    "layered_figure_rows",
    "launch_configured_metrics_dashboard",
    "launch_configured_qc_dashboard",
    "launch_metrics_dashboard",
    "launch_qc_dashboard",
    "load_dashboard_metric_dataset",
    "log2_effect_to_percent",
    "plot_data_synthetic_availability",
    "plot_event_station_retention_heatmap",
    "plot_event_magnitude_map",
    "plot_event_trace_comparison",
    "plot_observed_synthetic_record_section",
    "plot_event_radial_trace_section",
    "plot_post_qc_station_event_map",
    "plot_qc_drop_cause_diagnostics",
    "plot_record_section",
    "plot_retention_summary",
    "plot_station_event_beachball_map",
    "plot_station_event_network_map",
    "plot_station_event_waveform_map",
    "plot_trace_inventory_samples",
    "plot_waveform_overlay_matrix",
    "prepare_dashboard_metric_table",
    "queue_rows_from_filtered_trace_df",
    "read_figure_sidecar_metadata",
    "savefig",
    "sidecar_rows_for_write",
    "write_dashboard_metric_dataset",
    "write_configured_dashboard_datasets",
    "write_dashboard_summaries",
    "write_dashboard_summary_dataset",
    "write_figure_row_sidecar",
    "write_trace_qc_overview_html",
]
